name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add a Daily Commit (23f2005327@ds.study.iitm.ac.in)  
        run: |
          echo "Last updated: $(date)" >> daily-update.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "23f2005327@ds.study.iitm.ac.in"
          git add daily-update.txt
          git commit -m "Automated daily update: $(date)" || echo "No changes to commit"
          git push
