name: Example GitHub Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 23f2005327@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Another step
        run: echo "This is a test."
